### ISSUE TITLE
Error AttributeError: 'coroutine' object has no attribute '_set_loop'  RuntimeWarning: coroutine 'init_app' was never awaited

### ISSUE THREAD

**Issue by git579** [aio-libs/aiohttp-demos#44] opened 2018-09-24 18:33 UTC
I try command
`python3 aiohttpdemo_blog/main.py -c config/user_config.toml`
and get the error/ What i must to do
```
AttributeError: 'coroutine' object has no attribute '_set_loop'
sys:1: RuntimeWarning: coroutine 'init_app' was never awaited
```

**Comment by jettify** [comment] 2018-09-24 18:35
Probably missed `await` before `init_app`, would you like to fix demo?

**Comment by git579** [comment] 2018-09-24 18:37
I beginner  i cant

**Comment by gyermolenko** [comment] 2018-09-24 19:05
HI @git579 
I run the app with python 3.6.5/aiohttp3.2.1 or with python 3.7.0 / aiohttp3.4.4 successfully.
Can you share your configuration please?
Full traceback also could probably help.

**Comment by gyermolenko** [comment] 2018-10-08 11:20
closing since I wasn't able to reproduce the issue
@git579 feel free to reopen with more detiails

**Closed by gyermolenko** 2018-10-08 11:20 UTC
