### ISSUE TITLE
data is not getting populated while running `sample_data(engine)` while seeding the polls data

### ISSUE THREAD

**Issue by wajeshubham** [aio-libs/aiohttp-demos#1032] opened 2024-03-26 08:45 UTC
### Description:

While seeding the polls data in polls app the population is not getting reflected in database. Seems like the the auto-commit is not enabled by default because when I am doing `conn.commit()` the seeding works.

Code line: https://github.com/aio-libs/aiohttp-demos/blob/master/docs/tutorial.rst?plain=1#L350 (Adding `conn.commit()` above this line, before doing `conn.close()` populates the data correctly.)

Commit as you go reference: https://docs.sqlalchemy.org/en/20/core/connections.html#commit-as-you-go

I am happy to contribute if this is an issue and would love to know your thought on this.

Thank you!

**Comment by Dreamsorcerer** [comment] 2024-03-26 18:37
The code is sqlalchemy core v1, and needs to be updated.
Current attempt is in #428. Feel free to pick it up and resolve the remaining CI errors.

**Comment by Dreamsorcerer** [comment] 2024-03-26 18:38
I'm just going to close this as a duplicate of #365, as it will be resolved at that point regardless.

**Closed by Dreamsorcerer** 2024-03-26 18:38 UTC
